Started by user [8mha:////4JHX9KC+Nlo+OySbwnrCvHdweRsWBVwiMfqJbFXf44JWAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzWEgZu/dLi1CL9xJTczDwAj6GcLcAAAAA=[0mAdmin
Building in workspace /var/lib/jenkins/workspace/try22
################################################################################################################
  Parameterized Remote Trigger Configuration:
    - job:                     try 
    - remoteJenkinsName:       Remote
    - remoteJenkinsUrl:        http://13.127.139.222:8080
    - auth:                    'Credentials Authentication' as user 'jenkins' (Credentials ID 'jenkins')
    - parameters:              [string=hi]
    - blockBuildUntilComplete: false
    - connectionRetryLimit:    5
################################################################################################################
Connection to remote server failed [401], waiting for to retry - 10 seconds until next attempt. URL: http://13.127.139.222:8080/job/try/api/json, parameters: 
Retry attempt #1 out of 5
Connection to remote server failed [401], waiting for to retry - 10 seconds until next attempt. URL: http://13.127.139.222:8080/job/try/api/json, parameters: 
Retry attempt #2 out of 5
Connection to remote server failed [401], waiting for to retry - 10 seconds until next attempt. URL: http://13.127.139.222:8080/job/try/api/json, parameters: 
Retry attempt #3 out of 5
Connection to remote server failed [401], waiting for to retry - 10 seconds until next attempt. URL: http://13.127.139.222:8080/job/try/api/json, parameters: 
Retry attempt #4 out of 5
Connection to remote server failed [401], waiting for to retry - 10 seconds until next attempt. URL: http://13.127.139.222:8080/job/try/api/json, parameters: 
Retry attempt #5 out of 5
FATAL: Max number of connection retries have been exeeded.
org.jenkinsci.plugins.ParameterizedRemoteTrigger.exceptions.ExceedRetryLimitException: Max number of connection retries have been exeeded.
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:526)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:521)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:521)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:521)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:521)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.sendHTTPCall(HttpHelper.java:521)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.tryCall(HttpHelper.java:566)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.utils.HttpHelper.tryGet(HttpHelper.java:586)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.doGet(RemoteBuildConfiguration.java:843)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.getRemoteJobMetadata(RemoteBuildConfiguration.java:1012)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.performTriggerAndGetQueueId(RemoteBuildConfiguration.java:602)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.perform(RemoteBuildConfiguration.java:567)
	at org.jenkinsci.plugins.ParameterizedRemoteTrigger.RemoteBuildConfiguration.perform(RemoteBuildConfiguration.java:540)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Finished: FAILURE
